sudo: false

language: cpp

install:
  # Set the anaconda environment
  - curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels defaults
  - conda update -q --all
  - conda install conda-build anaconda-client
  # build
  - conda build --no-test -c $MY_CONDA_CHANNEL conda-recipe

script:
  - echo "No test scripts to be run!"

deploy:
  provider: script
  skip_cleanup: true
  script: anaconda -t $CONDA_TOKEN upload $HOME/miniconda/conda-bld/**/*.tar.bz2
  on:
    tags: true
