package:
    name: shimadzu_pump
    version: 1.1.6

build:
  number: 0

source:
    path: ..

requirements:
    build:
        - python
    run:
        - python
        - requests
        - pcaspy

build:
  entry_points:
    - shimadzu_pump_ioc = shimadzu_pump.run:main

about:
    summary: "Just a Shimadzu pump controller."
