package:
    name: shimadzu_pump
    version: 1.3.6

build:
    noarch: python
    number: 0
    script: python -m pip install --no-deps --ignore-installed .
    entry_points:
      - shimadzu_pump_ioc = shimadzu_pump.run:main

source:
    path: ..

requirements:
    build:
        - python
        - pip
    run:
        - python
        - requests
        - pcaspy

about:
    summary: "Just a Shimadzu pump controller. Docs at https://github.com/paulscherrerinstitute/shimadzu_pump"
