package:
    name: shimadzu_pump
    version: 1.3.7

build:
    number: 0
    entry_points:
      - shimadzu_pump_ioc = shimadzu_pump.run:main

source:
    path: ..

requirements:
    build:
        - python
    run:
        - python
        - requests
        - pcaspy

about:
    summary: "Just a Shimadzu pump controller. Docs at https://github.com/paulscherrerinstitute/shimadzu_pump"
